# packages in environment at /Users/rushil.chakrabarty/miniconda3/envs/attn_states:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
anyio                     4.4.0              pyhd8ed1ab_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
argcomplete               3.5.0                    pypi_0    pypi
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h80987f9_0  
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
black                     24.4.2          py312hca03da5_0  
blas                      1.0                    openblas  
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
bottleneck                1.3.7           py312ha86b861_0  
brotli                    1.0.9                h80987f9_8  
brotli-bin                1.0.9                h80987f9_8  
brotli-python             1.0.9           py312h313beb8_8  
bzip2                     1.0.8                h80987f9_6  
ca-certificates           2024.7.2             hca03da5_0  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.7.4        py312hca03da5_0  
cffi                      1.16.0          py312h80987f9_1  
cfgv                      3.4.0           py312hca03da5_0  
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
chex                      0.1.86                   pypi_0    pypi
click                     8.1.7           py312hca03da5_0  
cloudpickle               3.0.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
commitizen                3.29.0                   pypi_0    pypi
contourpy                 1.2.0           py312h48ca7d4_0  
cycler                    0.11.0             pyhd3eb1b0_0  
debugpy                   1.6.7           py312h313beb8_0  
decli                     0.6.2                    pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.8           py312hca03da5_0  
dm-tree                   0.1.8                    pypi_0    pypi
dynamax                   0.1.4                    pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
etils                     1.9.2                    pypi_0    pypi
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h313beb8_0  
fastprogress              1.0.3                    pypi_0    pypi
filelock                  3.13.1          py312hca03da5_0  
fonttools                 4.51.0          py312h80987f9_0  
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h1192e45_0  
gast                      0.6.0                    pypi_0    pypi
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
identify                  2.5.5           py312hca03da5_0  
idna                      3.8                pyhd8ed1ab_0    conda-forge
importlib-metadata        8.4.0              pyha770c72_0    conda-forge
importlib_metadata        8.4.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.4              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   8.26.0             pyh707e725_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jax                       0.4.31                   pypi_0    pypi
jaxlib                    0.4.31                   pypi_0    pypi
jaxtyping                 0.2.33                   pypi_0    pypi
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h80987f9_3  
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312hca03da5_0  
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.4              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4           py312h313beb8_0  
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libbrotlicommon           1.0.9                h80987f9_8  
libbrotlidec              1.0.9                h80987f9_8  
libbrotlienc              1.0.9                h80987f9_8  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_1  
libffi                    3.4.4                hca03da5_1  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libsodium                 1.0.18               h27ca646_1    conda-forge
libtiff                   4.5.1                h313beb8_0  
libwebp-base              1.3.2                h80987f9_0  
llvm-openmp               14.0.6               hc6e5704_0  
lz4-c                     1.9.4                h313beb8_1  
markupsafe                2.1.3           py312h80987f9_0  
matplotlib                3.8.4           py312hca03da5_0  
matplotlib-base           3.8.4           py312hd77ebd4_0  
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
ml-dtypes                 0.4.0                    pypi_0    pypi
mypy_extensions           1.0.0           py312hca03da5_0  
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
nodeenv                   1.7.0           py312hca03da5_0  
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.7           py312h0f3ea24_0  
numpy                     1.26.4          py312h7f4fdc5_0  
numpy-base                1.26.4          py312he047099_0  
openjpeg                  2.5.2                h54b8e55_0  
openssl                   3.0.14               h80987f9_0  
opt-einsum                3.3.0                    pypi_0    pypi
optax                     0.2.3                    pypi_0    pypi
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1            py312hca03da5_0  
pandas                    2.2.2           py312hd77ebd4_0  
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pathspec                  0.10.3          py312hca03da5_0  
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py312h80987f9_0  
pip                       24.2            py312hca03da5_0  
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              3.10.0          py312hca03da5_0  
pre-commit                3.8.0              pyha770c72_0    conda-forge
pre_commit                3.8.0                hd8ed1ab_0    conda-forge
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36                   pypi_0    pypi
psutil                    5.9.0           py312h80987f9_0  
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pybind11-abi              5                    hd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9           py312hca03da5_0  
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.4               h99e199e_1  
python-dateutil           2.9.0post0      py312hca03da5_2  
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd3eb1b0_0  
pytz                      2024.1          py312hca03da5_0  
pyyaml                    6.0.1           py312h80987f9_0  
pyzmq                     25.1.2          py312h313beb8_0  
questionary               2.0.1                    pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.10.6          py312hf0e4da2_0  
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.13.1          py312ha409365_0  
seaborn                   0.13.2          py312hca03da5_0  
send2trash                1.8.2           py312hca03da5_0  
setuptools                72.1.0          py312hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sqlite                    3.45.3               h80987f9_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tensorflow-probability    0.24.0                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
terminado                 0.18.1             pyh31c8845_0    conda-forge
threadpoolctl             3.5.0                    pypi_0    pypi
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.14               h6ba3021_0  
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.13.2                   pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
tornado                   6.4.1           py312h80987f9_0  
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typeguard                 2.13.3                   pypi_0    pypi
types-python-dateutil     2.9.0.20240821     pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h04d1e81_0  
ukkonen                   1.0.1           py312h48ca7d4_0  
unicodedata2              15.1.0          py312h80987f9_0  
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_0    conda-forge
virtualenv                20.26.1         py312hca03da5_0  
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.8.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0          py312hca03da5_0  
xz                        5.4.6                h80987f9_1  
yaml                      0.2.5                h1a28f6b_0  
zeromq                    4.3.5                h313beb8_0  
zipp                      3.20.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h18a0788_1  
zstd                      1.5.5                hd90d995_2  
